# Generated by Django 5.1.3 on 2024-12-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0003_alter_invoice_options_alter_package_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SshCruise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssh_trip_trip_id", models.CharField(max_length=5)),
                ("ssh_passenger_passenger_id", models.IntegerField()),
                ("group_id", models.CharField(max_length=8)),
                ("ssh_stateroom_stateroom_id", models.IntegerField()),
                ("ssh_sides_side_id", models.IntegerField()),
            ],
            options={
                "db_table": "ssh_cruise",
            },
        ),
        migrations.CreateModel(
            name="SshPackageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_id", models.IntegerField()),
                ("trip_id", models.CharField(max_length=5)),
                ("passenger_id", models.IntegerField()),
                ("group_id", models.CharField(max_length=8)),
            ],
            options={
                "db_table": "ssh_package_info",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="package",
            options={},
        ),
        migrations.AlterModelOptions(
            name="passenger",
            options={},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="side",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stateroom",
            options={},
        ),
    ]
