# Generated by Django 5.1.3 on 2024-12-04 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0005_remove_invoice_date_alter_passenger_blood_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="package",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="passenger",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="side",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sshcruise",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sshpackageinfo",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="stateroom",
            options={"managed": False},
        ),
    ]
