# Generated by Django 5.1.3 on 2024-12-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0006_alter_invoice_options_alter_package_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SshTrSrS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("trip_id", models.CharField(max_length=5)),
            ],
            options={
                "db_table": "ssh_tr_sr_s",
                "managed": False,
            },
        ),
    ]
