# Generated by Django 5.1.3 on 2024-12-07 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0007_sshtrsrs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"managed": True},
        ),
    ]
