# Generated by Django 5.1.3 on 2024-12-07 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0008_alter_payment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="invoice",
        ),
    ]
