# Generated by Django 5.1.3 on 2024-12-07 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssh_cruise", "0009_remove_payment_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="ssh_invoice_invoice_id",
            field=models.ForeignKey(
                db_column="ssh_invoice_invoice_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ssh_cruise.invoice",
            ),
            preserve_default=False,
        ),
    ]
